### ISSUE TITLE
Unmarshaler interface doesn't work on inlined fields

### ISSUE THREAD

**Issue by wrouesnel** [go-yaml/yaml#125]
So I've been trying to implement a config system where a lot of higher-order constructs inherit parameters from lower objects.

The problem I've found is that if I have two structs, Parent and Child, and Child contains Parent as an anonymous struct, then I can only get the fields of Child to unmarshal successfully if Parent does not have a custom UnmarshalYAML() function.

If a custom UnmarshalYAML() function is supplied, then only the nested structs fields will be populated - the top is set to nil.

Example - this works fine:

``` go
package main

import (
    "fmt"
    "gopkg.in/yaml.v2"
)

type Parent struct {
    DNA string          `yaml:"dna"`
}

type Child struct {
    Parent              `yaml:",inline"`
    Phenotype string    `yaml:"phenotype"`  
}

func main() {
    y := `
dna: AAAAGGGGTTTTCCCC
phenotype: Red Hair
`

    child := new(Child)
    err := yaml.Unmarshal([]byte(y),child)
    if err != nil {
        fmt.Println(err)
    }

    fmt.Println(child)
}
```

Result: `&{{AAAAGGGGTTTTCCCC} Red Hair}`

But this does not:

``` go
package main

import (
    "fmt"
    "gopkg.in/yaml.v2"
)

type Parent struct {
    DNA string          `yaml:"dna"`
}

func (this *Parent) UnmarshalYAML(unmarshal func(interface{}) error) error {
    type plain Parent
    if err := unmarshal((*plain)(this)); err != nil {
        fmt.Println("Parent :", err)    
        return nil
    }

    return nil
}

type Child struct {
    Parent              `yaml:",inline"`
    Phenotype string    `yaml:"phenotype"`  
}

func main() {
    y := `
dna: AAAAGGGGTTTTCCCC
phenotype: Red Hair
`

    child := new(Child)
    err := yaml.Unmarshal([]byte(y),child)
    if err != nil {
        fmt.Println(err)
    }

    fmt.Println(child)
}
```

Result: `&{{AAAAGGGGTTTTCCCC} }`

It also fails if skip the type indirection:

``` go
package main

import (
    "fmt"
    "gopkg.in/yaml.v2"
)

type Parent struct {
    DNA string          `yaml:"dna"`
}

func (this *Parent) UnmarshalYAML(unmarshal func(interface{}) error) error {
    tgt := make(map[string]interface{})

    if err := unmarshal(tgt); err != nil {
        fmt.Println("Parent :", err)    
        return nil
    }

    return nil
}

type Child struct {
    Parent              `yaml:",inline"`
    Phenotype string    `yaml:"phenotype"`  
}

func main() {
    y := `
dna: AAAAGGGGTTTTCCCC
phenotype: Red Hair
`

    child := new(Child)
    err := yaml.Unmarshal([]byte(y),child)
    if err != nil {
        fmt.Println(err)
    }

    fmt.Println(child)
}
```

Result: `&{{} }`

**Comment by 3rf** [comment]
+1 I hit this today

**Comment by index0h** [comment]
+1

**Comment by niemeyer** [comment]
This has been fixed in v3. Will close this issue once it is widely available.

**Comment by jonasrmichel** [comment]
@niemeyer -- I'm still encountering this behavior using the latest changes from the `v3` branch.

https://play.golang.org/p/QTHL0cjZC1m

**Comment by vito** [comment]
@jonasrmichel It seems to only detect the new `Unmarshaler` interface in v3:

https://github.com/go-yaml/yaml/blob/c07216459f38720d049ae4631eded7e2224ba7ba/yaml.go#L18-L22

However, with if I update your example with this I end up with this output:

```
&main.Child{Phenotype:"", Parent:main.Parent{DNA:"AAAAGGGGTTTTCCCC"}}
```

So the parent got its fields, but not the child. I believe this is a problem with the example: the child type embeds the parent, thereby inheriting the `UnmarshalYAML` method which unintentionally gets called when trying to decode into the child type.

If I fix this, it works: https://play.golang.org/p/LJyhq3iQmEx

```
&main.Child{Phenotype:"Red Hair", Parent:main.Parent{DNA:"AAGGTCTGA"}}
```

(Note the uppercased DNA value, which shows that `UnmarshalYAML` was called.)

---

It looks like the obsolete `UnmarshalYAML(func(interface{}) error)` type is supported for backwards compatibility during regular unmarshalling, but not in this case, so this could be a subtle gotcha for folks upgrading from v2 to v3 since the compiler won't help you notice and you might think you don't have to update your types.

FWIW I like the new interface better and it's nice that it's a trivial code change, so maybe that's fine, since this wouldn't have been working code before anyway.
