### ISSUE TITLE
Unstable marshalled output for map with keys containing numbers

### ISSUE THREAD

**Issue by prashantv** [go-yaml/yaml#194]
When comparing map keys, if both keys contain a number starting with the same digit, then there's a bug in the comparison.

This test reproduces the multiple orders:

``` go
package main

import (
    "fmt"
    "os"

    yaml "gopkg.in/yaml.v2"
)

func main() {
    vals := map[string]int{"a/100": 1, "a/17": 2, "a/20": 3}
    generated := make(map[string]struct{})
    for i := 0; i < 100; i++ {
        contents, err := yaml.Marshal(vals)
        if err != nil {
            panic(err)
        }
        generated[string(contents)] = struct{}{}
    }

    if len(generated) != 1 {
        fmt.Println("Generated multiple outputs")
        for k := range generated {
            fmt.Println(k)
            fmt.Println("----")
        }
        os.Exit(-1)
    }
}
```

The output is:

```
Generated multiple outputs
a/17: 2
a/20: 3
a/100: 1

----
a/20: 3
a/100: 1
a/17: 2

----
a/100: 1
a/17: 2
a/20: 3

----
exit status 255
```

The issue is when skipping runes if they are the same. This causes issues when skipping digits, since comparing `a/100` to `a/17` leads to the `1` being skipped, and then the values are compared as `00` vs `7`. This leads to `a/100` sorting to less than `a/17`. However, if the values were compared with `a/20` instead, the values are sorted in the correct order.

**Comment by benfleis** [comment]
+1

Can this get some love?

**Comment by prashantv** [comment]
@niemeyer Would you be able to take a look at this?

**Comment by vinzenz** [comment]
Actually this is not a problem with numbers. This is just this: 

> When iterating over a map with a range loop, the iteration order is not specified and is not guaranteed to be the same from one iteration to the next. Since Go 1 the runtime randomizes map iteration order, as programmers relied on the stable iteration order of the previous implementation. If you require a stable iteration order you must maintain a separate data structure that specifies that order. This example uses a separate sorted slice of keys to print a map[int]string in key order:

See: https://blog.golang.org/go-maps-in-action # Iteration order

**Comment by prashantv** [comment]
@vinzenz The yaml marshaller produces a stable output by iterating over keys in sorted order, if you saw the code here:
https://github.com/prashantv/yaml/blob/v2/sorter.go

I am aware of map iteration order being undefined, but marshallers typically have stable output (try `json.Marshal`), which is typically achieved by iterating over the map in sorted key order. The issue here is that the sorting has a bug when dealing with numbers.

I have a fix for this issue in https://github.com/go-yaml/yaml/issues/195 which requires a minor change to the sorter. I was just hoping that @niemeyer would be able to review that change, since I'd like to avoid using a fork of this library.

**Comment by vinzenz** [comment]
@prashantv right, my bad didn't realize ;-)

**Comment by niemeyer** [comment]
This is fixed in https://github.com/go-yaml/yaml/commit/dcd83b31fd165d8cc8677fce58f889dca3e06f35, without significant changes to the algorithm overall behavior.

Please let me know how it goes.

**Comment by HeavyWombat** [comment]
Just in case someone comes here like me and thinks this is completely solved, I can still reproduce unstable map ordering with a use case I have. Run the following code a couple of times and you will observe different orders:
```go
package main

import (
	"fmt"

	"gopkg.in/yaml.v2"
)

const example = `
properties:
  cc:
    quota_definitions:
      q256MB:
        non_basic_services_allowed: true
      q2GB:
        non_basic_services_allowed: true
      q4GB:
        non_basic_services_allowed: true
`

func main() {
	var data interface{}
	if err := yaml.Unmarshal([]byte(example), &data); err == nil {
		if out, err := yaml.Marshal(data); err == nil {
			fmt.Println(string(out))
		}
	}
}

```

Tested with tag  `v2.2.1`.

**Comment by mkmik** [comment]
I can still observe this with v2.4.0

(code that reproduces the issue https://github.com/mkmik/yamlsortbug)

Doesn't happen in gopkg.in/yaml.v3

UPDATE: https://github.com/go-yaml/yaml/issues/444#issuecomment-481268195
> But what you've found is a bug. I've fixed it in cdc409d in v3. I'll backport it to v2 later.
