### ISSUE TITLE
blank lines do not round-trip

### ISSUE THREAD

**Issue by bboreham** [go-yaml/yaml#627]
I guess this is intentional since there's nowhere in the `Node` structure to store them, but I think it's good to have this noted as an issue.

```
package main

import (
        "fmt"

        "gopkg.in/yaml.v3"
)

var data = `
a: Easy!

b:
  c: 2
`

func main() {
        t := yaml.Node{}
        _ = yaml.Unmarshal([]byte(data), &t)
        d, _ := yaml.Marshal(&t)
        fmt.Printf("%s\n", string(d))
}
```
```
a: Easy!
b:
    c: 2
```
https://play.golang.org/p/Wc5wR4CO10I

**Comment by niemeyer** [comment]
Done with eeeca48.

**Comment by aakrem** [comment]
can't we add something like blanklines-till-the-next-node? and add it to the node structure ??
Would be nice to reopen this issue

**Comment by mikefarah** [comment]
This has not been fixed...the provided example in the issue still has it's newlines stripped..

That or it has regressed? @niemeyer

**Comment by mikefarah** [comment]
oh just saw that the commit is a comment and not a fix - my bad

**Comment by omerozery** [comment]
everyone is just OK with that ?

**Comment by bboreham** [comment]
Everyone is very grateful to have such high-quality software freely available.

**Comment by robrecord** [comment]
Please can we re-open this. It is an issue.

**Comment by andry81** [comment]
Go programmers just go out of chat.  :/

**Comment by ricosega** [comment]
shouldn't this be reopened?
