### ISSUE TITLE
Improve rendering of text with embedded newlines

### ISSUE THREAD

**Issue by DmitriyMV** [go-yaml/yaml#70]
When I try to Marshal multiline string containing '/' or non-english symbols, for examle, I get this:

```
- text: Python script start
  note: "#!/usr/bin/env python3\n# -*- coding: utf-8 -*- \n"
```

and original yaml looked likes this

```
- text: Python script start
  note: |
    #!/usr/bin/env python3
    # -*- coding: utf-8 -*-
```

Is this intentional behavior? And if so, can I do something with it? Because its really hard to read multiline strings in form like "str\nstr2\n".

**Comment by niemeyer** [comment]
It is correct, but I agree it's not ideal. Let's fix it so that it marshals as a literal.

**Comment by rogpeppe** [comment]
This has been fixed.

**Comment by flibustenet** [comment]
Sorry, i still have the same problem, could you show me where is the code for this that i can look if i missed somethings ?

**Comment by lllama** [comment]
Don't like "me too"ing but I'm seeing similar output. It would be nice to have the option of setting strings as literals.
